apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: shinhyeonsik/hello-world:26
          ports:
            - containerPort: 8080